#!/bin/sh

# Migrate emailrelay from sf svn to a git repository using svn-all-fast-export

export FILTER_BRANCH_SQUELCH_WARNING=1

set -e

for cmd in svnsync svn-all-fast-export ; do
  if ! command -v "$cmd" > /dev/null 2>&1 ; then
    >&2 echo "This script requires $cmd to run."
    exit 1
  fi
done

svnsync synchronize "file://$(pwd)/svn" https://svn.code.sf.net/p/emailrelay/code/

if [ -e emailrelay ] ; then
  rm -rf emailrelay
fi

svn-all-fast-export --rules rules --svn-branches --identity-map authors --add-metadata svn
git repack -a -d -f

if [ ! -e kde-ruleset ] ; then
  git clone https://github.com/KDE/kde-ruleset
fi

(
  cd kde-ruleset
  git remote update --prune
  git reset --hard origin/master
  sed 's/\.XXXXX /.XXXXXX /g' bin/filter-goodies > bin/filter-goodies.new && mv bin/filter-goodies.new bin/filter-goodies
)

RULESETDIR="$(pwd)"/kde-ruleset
export RULESETDIR

(
  cd emailrelay
  git update-ref -d refs/tags/backups/g_walker@309
  git update-ref -d refs/tags/backups/V_2_3@291

  "$RULESETDIR/bin/parent-adder" ../parent-map
  "$RULESETDIR/bin/remove-fb-backup-refs.sh"

  "$RULESETDIR/bin/fix-tags"
  "$RULESETDIR/bin/remove-fb-backup-refs.sh"

  FIX_TAGS_NONCVS=1 "$RULESETDIR/bin/fix-tags"
  "$RULESETDIR/bin/remove-fb-backup-refs.sh"

  git reflog expire --expire=now --all
  git gc --prune=now
  git gc --aggressive --prune=now
)
